title = "Toasty"

gitSourceBranch = "main"
changelog = false

[[classOrder]]
classes = ["Toasty"]

[[classOrder]]
section = "Core"
classes = [
	"Lifecycle",
	"LifecycleManager",
	"SingletonManager",
	"Types"
]

[[classOrder]]
section = "Networking"
classes = [
	"ServerEventReceiver",
	"ServerEventSender",
	"ClientEventReceiver",
	"ClientEventSender"
]


[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

[footer]
style = "dark"
copyright = "Copyright Â© 2025 Its a bit random. Built with Moonwave and Docusaurus"