[package]
name = "its-a-bit-random/toasty"
description = "Powerful game framework"
version = "1.1.1"

license = "MIT"
authors = ["Sebastian2852"]

realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

exclude = ["**"]
include = ["default.project.json", "Toasty", "Toasty/**", "LICENSE", "wally.toml"]
private = false

[dependencies]
Promise = "lukadev-0/typed-promise@4.0.2"
Signal = "sleitnick/signal@2.0.3"